### ISSUE TITLE
Refactor ACL

### ISSUE THREAD

**Issue by paulomcnally** [uca-isti/api-0209-1-20171C#3]
Los ACL no son correctos.

**Comment by paulomcnally** [comment]
Chicos por favor verificar el ACL actual, especifique que cualquiera pueda leer el modelo place (find), pero que nadie pueda editar, actualizar o eliminar.

Podemos ampliar esta lógica hablandolo.

Saludos @Adriano98 @draenwing @LeoAbdel @RoxanaRRS

**Comment by GuillermoDrivApp** [comment]
Profe, saludos.

le escribo debido a que este proyecto de github no me corresponde, el mío es GRUPO #3 api-0204, por lo tanto yo usuario "GuillermoDrivApp" no debo estar enlazado a este....
saludos [😃]


________________________________
De: Paulo McNally <notifications@github.com>
Enviado: martes, 21 de febrero de 2017 02:54 p.m.
Para: uca-isti/api-0209-1-20171C
Cc: GuillermoDrivApp; Mention
Asunto: Re: [uca-isti/api-0209-1-20171C] Refactor ACL (#3)


Chicos por favor verificar el ACL actual, especifique que cualquiera pueda leer el modelo place (find), pero que nadie pueda editar, actualizar o eliminar.

Podemos ampliar esta lógica hablandolo.

Saludos @Adriano98<https://github.com/Adriano98> @draenwing<https://github.com/draenwing> @LeoAbdel<https://github.com/LeoAbdel> @GuillermoDrivApp<https://github.com/GuillermoDrivApp> @RoxanaRRS<https://github.com/RoxanaRRS>

**Comment by paulomcnally** [comment]
@GuillermoDrivApp sorry, me saliste en las recomendaciones a mencionar. 

Saludos

:)

**Comment by GuillermoDrivApp** [comment]
Tranquilo profe [😃]


________________________________
De: Paulo McNally <notifications@github.com>
Enviado: miércoles, 22 de febrero de 2017 01:31 p.m.
Para: uca-isti/api-0209-1-20171C
Cc: GuillermoDrivApp; Mention
Asunto: Re: [uca-isti/api-0209-1-20171C] Refactor ACL (#3)


@GuillermoDrivApp<https://github.com/GuillermoDrivApp> sorry, me saliste en las recomendaciones a mencionar.

Saludos

:)
